import os
import subprocess
import shutil
import json
from pathlib import Path
from llama_index.llms.gemini import Gemini

# Restricted list of allowed commands for security
ALLOWED_COMMANDS = ["ls", "pytest", "python", "npm", "yarn", "pip", "git", "echo"]

def edit_file(filepath, content):
    """
    Overwrites the file with new content.
    """
    try:
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, "w") as f:
            f.write(content)
        print(f"File {filepath} updated successfully.")
        return True
    except Exception as e:
        print(f"Error editing file {filepath}: {e}")
        return False

def run_command(command, cwd="."):
    """
    Executes a shell command and returns the output and exit code.
    Includes basic security checks.
    """
    if not command:
        return {"stdout": "", "stderr": "No command provided", "returncode": -1}

    base_cmd = command.split()[0]
    if base_cmd not in ALLOWED_COMMANDS:
        return {
            "stdout": "",
            "stderr": f"Security Error: Command '{base_cmd}' is not in the allowed list: {ALLOWED_COMMANDS}",
            "returncode": -1
        }

    try:
        result = subprocess.run(
            command,
            shell=True,
            capture_output=True,
            text=True,
            cwd=cwd
        )
        return {
            "stdout": result.stdout,
            "stderr": result.stderr,
            "returncode": result.returncode
        }
    except Exception as e:
        return {
            "stdout": "",
            "stderr": str(e),
            "returncode": -1
        }

def scaffold_component(name, target_dir, prompt):
    """
    Uses Gemini LLM to generate a real monorepo component with multiple files.
    """
    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        print("GOOGLE_API_KEY not found. Falling back to mock scaffolding.")
        mock_files = {
            "main.py": f"# {name} generated by Monorepo Agent (MOCK)\ndef run():\n    print('Hello from {name}')",
            "README.md": f"# {name}\n\nGenerated for: {prompt}"
        }
        return create_component_files(name, target_dir, mock_files)

    try:
        llm = Gemini(model="models/gemini-2.0-flash", api_key=api_key)

        system_prompt = """
        You are a monorepo component scaffolder.
        You MUST return ONLY a JSON object where keys are filenames and values are the file content.
        Do not include any other text, markdown blocks, or explanation.
        The component is a new service in a monorepo.
        Focus on providing a clean, working template based on the user description.
        Example format:
        {"main.py": "print('hello')", "README.md": "# My Service"}
        """

        user_prompt = f"Create a new component named '{name}' with the following description: {prompt}"

        response = llm.complete(f"{system_prompt}\n\n{user_prompt}")

        # Extract JSON from response (handling potential markdown blocks if LLM ignores instructions)
        response_text = response.text.strip()
        if response_text.startswith("```json"):
            response_text = response_text.replace("```json", "").replace("```", "").strip()
        elif response_text.startswith("```"):
            response_text = response_text.replace("```", "").strip()

        files_data = json.loads(response_text)
        return create_component_files(name, target_dir, files_data)

    except Exception as e:
        print(f"Error scaffolding component with Gemini: {e}")
        return False

def create_component_files(name, target_dir, files_data):
    """
    Physically creates the files on disk for a scaffolded component.
    """
    if ".." in name or "/" in name:
        return False

    component_path = Path(target_dir) / name
    try:
        if component_path.exists():
            print(f"Component {name} already exists at {component_path}")
            return False

        os.makedirs(component_path, exist_ok=True)
        for filename, content in files_data.items():
            file_path = component_path / filename
            edit_file(str(file_path), content)

        print(f"Scaffolded component {name} in {target_dir}")
        return True
    except Exception as e:
        print(f"Error creating files: {e}")
        return False

def self_healing_execution(command, filepath=None, fix_logic=None, max_retries=3):
    """
    Runs a command and if it fails, attempts to heal the code.
    """
    retries = 0
    while retries < max_retries:
        print(f"Executing command: {command} (Attempt {retries + 1})")
        result = run_command(command)

        if result["returncode"] == 0:
            return result

        if fix_logic and filepath:
            fix_logic(filepath, result["stderr"])
            retries += 1
        else:
            return result
    return result

if __name__ == "__main__":
    res = run_command("ls -l")
    print(res["stdout"])
